IntenetShop/InternetShop.Web/Controllers/ApplicationTypeController.cs
using IntenetShop.Domain.Entities;
using InternetShop.Application.Intefaces;
using InternetShop.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace InternetShop.Web.Controllers
{
    public class ApplicationTypeController : Controller
    {
        private readonly IApplicationTypeRepository _repository;
        public ApplicationTypeController(IApplicationTypeRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index()
        {
            var applicationTypes = _repository.GetAll();

            var model = applicationTypes.Select(c => new ApplicationTypeViewModel
            {
                Id = c.Id,
                Name = c.Name,

            })
            .ToList();

            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ApplicationTypeViewModel model)
        {
            if (!ModelState.IsValid)
                return View();

            var applicationType = new ApplicationType
            {
                Name = model.Name,
            };

            _repository.Add(applicationType);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var applicationType = _repository.GetById(id);
            var model = new ApplicationTypeViewModel
            {
                Name = applicationType.Name,
            };

            return View(model);
        }
        [HttpPost]
        public IActionResult Edit(ApplicationTypeViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var applicationType = new ApplicationType
            {
                Id = model.Id,
                Name = model.Name
            };
            _repository.Update(applicationType);

            return RedirectToAction("Index");

        }
        public IActionResult Delete(int id)
        {
            var applicationType = _repository.GetById(id);
            _repository.Remove(applicationType);

            return RedirectToAction("Index");
        }
    }
}

IntenetShop/InternetShop.Web/Controllers/CategoryController.cs
using IntenetShop.Domain.Entities;
using InternetShop.Application.Intefaces;
using InternetShop.Presistance.Repository;
using InternetShop.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace InternetShop.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _repository;
        public CategoryController(ICategoryRepository repository)
        {
            _repository = repository;
        }
        public IActionResult Index()
        {
            var categories = _repository.GetAll();

            var model = categories.Select(c => new CategoryViewModel
            {
                Id = c.Id,
                Name = c.Name,

            })
            .ToList();

            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(CategoryViewModel model)
        {
            if (!ModelState.IsValid)
                return View();

            var category = new Category
            {
                Name = model.Name,
            };
         
            _repository.Add(category);  

           return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id) 
        {
            var category = _repository.GetById(id);
            var model = new CategoryViewModel
            {
                Name = category.Name,
            };

            return View(model);
        }
        [HttpPost]
        public IActionResult Edit(CategoryViewModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var category = new Category
            {
                Id = model.Id,
                Name = model.Name
            };
            _repository.Update(category);

            return RedirectToAction("Index");
        
        }
        public IActionResult Delete(int id)
        {
            var category = _repository.GetById(id);
            _repository.Remove(category);

            return RedirectToAction("Index");
        }
    }
}

IntenetShop/InternetShop.Web/Controllers/ProductController.cs
using IntenetShop.Domain.Entities;
using InternetShop.Application.Intefaces;
using InternetShop.Web.Models;
using InternetShop.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InternetShop.Web.Controllers
{
    public class ProductController : Controller
       
    {
        private readonly IProductRepository _productRepository;
        private readonly ImageService _imageService;
        private readonly ProductService _productService; 

        public ProductController(IProductRepository productRepository, ImageService imageService, ProductService productService)
        {
            _productRepository = productRepository;
           
            _imageService = imageService;
            _productService = productService;
        }

        public IActionResult Index()
        {
            var entity = _productRepository.GetProducts();
            var product = entity.Select(p => new ProductViewModel
            {
                Id = p.Id,
                Name = p.Name,
                Price = p.Price,
                Category = p.Category,
                ApplicationType = p.ApplicationType
            

            }).ToList();
            return View(product);
        }
        [HttpGet]
        public IActionResult Create()
        {
           
            var products = new ProductViewModel
            {
                CategoryDropDown = _productService.GetCategoryList(),
                ApplicationTypeDropDown = _productService.GetApplicationTypeList(),

            };
            return View(products);
            
        }
        [HttpPost]
        public IActionResult Create(ProductViewModel product)
        {
            if (!ModelState.IsValid)
            {
                product.CategoryDropDown= _productService.GetCategoryList();
                product.ApplicationTypeDropDown= _productService.GetApplicationTypeList();
                return View(product);
            }
            var files = HttpContext.Request.Form.Files;
            product.Image = _imageService.ImageLoad(files);

            var entity = new Product
            {
                Name = product.Name,
                Price = product.Price,
                Description = product.Description,
                Image = product.Image,
                CategoryId = product.CategoryId,
                ApplicationTypeId= product.ApplicationTypeId,
            };
            _productRepository.Add(entity);

            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var entity = _productRepository.GetById(id);
            var product = new ProductViewModel
            {
                Name = entity.Name,
                Price = entity.Price,
                Description = entity.Description,
                Image = _imageService.imagePath + entity.Image,
                CategoryId= entity.CategoryId,
                CategoryDropDown = _productService.GetCategoryList(),
                ApplicationTypeId= entity.ApplicationTypeId,
                ApplicationTypeDropDown = _productService.GetApplicationTypeList(),
            };

            return View(product);

        }
        [HttpPost]
        public IActionResult Edit(ProductViewModel product)
        {
            if(!ModelState.IsValid) {
                return View(product);
            }

            var currentProduct = _productRepository.GetProductById(product.Id);
            _imageService.DeleteImage(currentProduct.Image);

            var files = HttpContext.Request.Form.Files;

            var entity = new Product
            {
                Id = product.Id,
                Name = product.Name,
                Description = product.Description,
                Price = product.Price,
                Image = _imageService.ImageLoad(files),
                CategoryId = product.CategoryId,
                
            };

            _productRepository.Update(entity);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var currentProduct = _productRepository.GetProductById(id);
            _imageService.DeleteImage(currentProduct.Image);
           
            _productRepository.Remove(currentProduct);

            return RedirectToAction("Index");

        }

    }
}

IntenetShop/InternetShop.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using InternetShop.Web.Common
@inject IHttpContextAccessor accessor

@{
    var sessionGet = accessor.HttpContext.Session.Get<List<ShoppingCart>>("SessionCart");
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InternetShop.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InternetShop.Web.styles.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/lib/fontawesome-free-6.4.0-web/css.all.win.css"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InternetShop.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApplicationType" asp-action="Index">ApplicationType</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        @if (sessionGet != null)
                        {
                            <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                <i class="fa fa-shopping-cart"></i> &nbsp;(@sessionGet.Count)
                            </a>
                        }
                        else
                        {
                            <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                <i class="fa fa-shopping-cart"></i> &nbsp;(0)
                            </a>
                            
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - InternetShop.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IntenetShop/InternetShop.Web/Views/Shared/_productCards.cshtml
@model ProductViewModel


<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(' ', '-')">
    <!--Card-->
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-left"><span class="text-info h5">@string.Format("{0:C0}", Model.Price)</span></label></div>
        </div>

        <img class="card-img-top img-fluid d-block mx-auto mb-3" src="@Model.Image" alt="" />
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge bg-dark p-2 border w-100" style="background-color:lavenderblush">@Model.Category.Name</span>
            </div>
            <div class="col-6 border-0">
                <span class="badge bg-dark p-2 border w-100" style="background-color:aliceblue">@Model.ApplicationType.Name</span>
            </div>
            <div class="col-12 p-1">
                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">Подробнее</a>
            </div>
        </div>
    </div>
</div>